import { StyleSheet } from "react-native";
import { colors } from '@/components/Colors';
import { textcolors } from '@/components/TextColors';
import { fonts } from '@/components/Fonts';

export const styles = StyleSheet.create({
  whiteBackground: {
    flex: 1,
    backgroundColor: colors.white,
  },
  screenContainer: {
    justifyContent: 'space-between',
    marginHorizontal: 25,
    marginVertical: 10,
  },
    namecontainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 25,
    },
    title: {
        fontSize: 48,
        fontFamily: fonts.bold,
        marginBottom: 10,
    },
    heading: {
        fontSize: 24,
        fontFamily: fonts.semiBold,
    },
    regularText: {
        fontSize: 20,
        fontFamily: fonts.regular
    },
    regText16: {
      fontSize: 16, 
      fontFamily: fonts.regular,
    },
    boldfont: {
      fontSize: 32,
      fontFamily: fonts.semiBold,
    },
    forgot: {
      fontSize: 20,
      color: textcolors.red,
      fontFamily: fonts.semiBold,
    },
    createacc: {
      color: textcolors.link,
      fontSize: 20,
      fontFamily: fonts.semiBold,
    },
    buttonContainer: {
      flexDirection: 'row',
      borderRadius: 20,
      marginHorizontal: 60,
      paddingVertical: 10,
      backgroundColor: '#5a7ead',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
      elevation: 2,
      shadowColor: colors.black,
    },
    buttonText: {
      fontFamily: fonts.bold,
      marginBottom: 20,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 5,
      paddingVertical: 14,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: textcolors.lightgrey,
      backgroundColor: colors.white,
    },
    focusedinput: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 5,
      paddingVertical: 14,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: colors.header,
      backgroundColor: colors.white,
    },
    container: {
      justifyContent: 'center',
      marginHorizontal: 20,
      marginBottom: 10,
    },
    secondcontainer: {
      justifyContent: 'left',
      marginBottom: 10,
    },
    littlenote: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 50,
      position: 'absolute',
      right: 0,
    },
    bluebottombar: {
      backgroundColor: colors.header,
      height: 100,
      top: 150,
    },
    searchInput: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: textcolors.darkgrey,
      backgroundColor: colors.grey,
      marginBottom: 10,
    },
    addButton: {
      position: 'absolute',
      bottom: 20,
      right: 20,
      backgroundColor: '#10386D',
      borderRadius: 150,
      padding: 5,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
    },
    cancelAddButton: {
      position: 'absolute',
      bottom: 20,
      right: 20,
      backgroundColor: colors.grey,
      borderRadius: 10,
      padding: 5,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
    },
    greybutton: {
      flexDirection: 'row',
      borderRadius: 15,
      paddingHorizontal: 15,
      paddingVertical: 5,
      backgroundColor: colors.othergrey,
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 10,
      elevation: 2,
      shadowColor: colors.black,
  },
})

export const styles_survey = StyleSheet.create({
  optionsContainer: {
    marginTop: 20,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.lightgrey,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
  },
  optionLabel: {
    fontSize: 18,
    marginLeft: 10,
    flex: 1,
  },
  optionIcon: {
    width: 30,
    height: 30,
    marginLeft: 10,
    resizeMode: 'contain',
  },
  searchContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.grey,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 15,
    fontSize: 16,
    fontFamily: fonts.regular,
    marginRight: 10,
  },
  infoText: {
    textAlign: 'center',
    color: textcolors.darkgrey,
    marginVertical: 10,
  },
  searchResultsList: {
    // maxHeight: 200,
    marginBottom: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.othergrey,
    borderRadius: 8,
    elevation: 1,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightgrey,
  },
  resultLabel: {
    flex: 1,
    fontSize: 16,
    fontFamily: fonts.regular,
  },
  dislikedListContainer: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: colors.othergrey,
    paddingTop: 15,
  },
  dislikedListTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: fonts.bold,
    marginBottom: 10,
  },
  dislikedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightgrey,
  },
  dislikedText: {
    fontSize: 16,
    fontFamily: fonts.regular,
    flex: 1,
    marginRight: 10,
  },
  inputGroup: {
    marginVertical: 20,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    color: textcolors.darkgrey,
    marginBottom: 8,
    fontFamily: fonts.regular,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.grey,
    backgroundColor: colors.white,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    fontSize: 18,
    fontFamily: fonts.regular,
    color: textcolors.black,
  },
})

export const styles_buttons = StyleSheet.create({
  checklist: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  greybox: {
    backgroundColor: colors.lightgrey,
    borderRadius: 10,
  },
  whitebox: {
    backgroundColor: colors.white,
    borderRadius: 10,
  },
  nextbutton: {
    borderRadius: 100,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#91A9C8',
    height: 170,
    width: 170,
    position: 'absolute',
    elevation: 2,
    shadowColor: colors.black,
  },
  searchButton: {
    backgroundColor: colors.header,
    padding: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
})